// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsiiedactvlzdvprwgkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzaWllZGFjdHZsemR2cHJ3Z2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODYzMTcsImV4cCI6MjA2Mzg2MjMxN30.dKVCTJvcY9x8Q8oMUwv8J_InQCc4QFEv_uvI7VSWWAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);